const db = require('../config/db');
const fs = require('fs');
const path = require('path');

// Read and execute schema
const schemaPath = path.join(__dirname, 'schema.sql');
const schema = fs.readFileSync(schemaPath, 'utf8');

// Execute schema statements
const statements = schema.split(';').filter(s => s.trim());
for (const statement of statements) {
  if (statement.trim()) {
    db.exec(statement);
  }
}

console.log('Schema created successfully!');

// Seed data
const robots = [
  { id: 1, name: "Nexus HomeHub", category: "Household", price: 2499, image: "https://images.unsplash.com/photo-1589254065878-42c014d8834b?w=400&h=300&fit=crop", short_desc: "All-in-one home assistant that manages schedules, controls smart devices, and helps with daily tasks.", description: "Nexus HomeHub is your personal home command center. It connects to all smart home devices, manages family schedules, reads recipes while you cook, makes video calls, and provides weather and news updates. Features a 10-inch interactive display with a friendly animated face for natural conversations.", specs: { display: "10-inch HD", battery: "12 hours (docked charging)", connectivity: "Wi-Fi 6 + Bluetooth 5.2 + Zigbee", weight: "4.2 kg", languages: "15+" }, highlight: "Smart Home Control", tags: ["smart home", "assistant", "family"], rating: 4.7, in_stock: true },
  { id: 2, name: "Nexus Butler", category: "Household", price: 4999, image: "https://images.unsplash.com/photo-1546776310-eef45dd6d63c?w=400&h=300&fit=crop", short_desc: "Mobile household robot that carries items, serves food, and assists elderly or disabled family members.", description: "Nexus Butler moves around your home autonomously, carrying groceries from the door, serving drinks and snacks, delivering laundry between rooms, and providing physical support for elderly family members. Its sturdy tray system holds up to 15kg and it navigates multi-room layouts with ease.", specs: { payload: "15 kg", speed: "1.2 m/s", battery: "10 hours", weight: "28 kg", navigation: "LiDAR + 3D Camera" }, highlight: "Heavy Carrier", tags: ["mobility", "elderly care", "carrying"], rating: 4.5, in_stock: true },
  { id: 3, name: "Nexus Chef Mini", category: "Household", price: 3299, image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop", short_desc: "Countertop cooking assistant that preps ingredients, stirs, and monitors cooking with precision timing.", description: "Nexus Chef Mini sits on your kitchen counter and takes over the tedious parts of cooking. It chops vegetables with interchangeable blade attachments, stirs pots at the right speed, monitors temperature with infrared sensors, and alerts you at each step. Connects to a recipe app with 2000+ guided recipes.", specs: { recipes: "2000+", blades: "6 attachments", sensors: "IR temp + weight", weight: "8.5 kg", power: "800W" }, highlight: "Precision Cooking", tags: ["cooking", "kitchen", "automation"], rating: 4.6, in_stock: true },
  { id: 4, name: "Nexus PetPal", category: "Household", price: 1299, image: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=400&h=300&fit=crop", short_desc: "Pet companion robot that feeds, plays with, and monitors your pets while you are away.", description: "Nexus PetPal keeps your furry friends happy when you are at work. It dispenses food on schedule, plays interactive laser and ball games, streams live video to your phone, and sends alerts if your pet shows unusual behavior. Built-in treat dispenser rewards good behavior.", specs: { food_capacity: "2 kg hopper", camera: "1080p wide-angle", battery: "18 hours", weight: "3.8 kg", connectivity: "Wi-Fi + App" }, highlight: "Pet Monitoring", tags: ["pets", "feeding", "monitoring"], rating: 4.8, in_stock: true },
  { id: 5, name: "Nexus CleanBot Pro", category: "Home Cleaner", price: 899, image: "https://images.unsplash.com/photo-1518314916381-77a37c2a49ae?w=400&h=300&fit=crop", short_desc: "Premium vacuum and mop combo robot with room-by-room mapping and no-go zones.", description: "CleanBot Pro maps your entire home in one pass and lets you set cleaning schedules per room. Its dual-action system vacuums and mops simultaneously with 4000Pa suction power. Automatically returns to its dock to empty the dustbin and refill the water tank.", specs: { suction: "4000 Pa", battery: "180 min", dustbin: "500 ml (auto-empty)", water_tank: "300 ml", noise: "55 dB" }, highlight: "Strongest Suction", tags: ["vacuum", "mopping", "auto-empty"], rating: 4.7, in_stock: true },
  { id: 6, name: "Nexus WindowWiz", category: "Home Cleaner", price: 599, image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=300&fit=crop", short_desc: "Window cleaning robot that handles glass surfaces of any size with suction-grip technology.", description: "WindowWiz sticks to any glass surface using powerful suction motors and cleans windows, glass walls, and mirrors streak-free. It plans an efficient zigzag path, detects edges automatically, and has a safety rope backup. Works on framed and frameless windows.", specs: { suction: "2800 Pa hold", speed: "4 min/sqm", safety: "Anti-fall + backup rope", noise: "62 dB", weight: "2.1 kg" }, highlight: "Window Specialist", tags: ["windows", "glass", "suction-grip"], rating: 4.3, in_stock: true },
  { id: 7, name: "Nexus PoolDive", category: "Home Cleaner", price: 1499, image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop", short_desc: "Robotic pool cleaner that scrubs walls, floor, and waterline automatically.", description: "PoolDive dives into your swimming pool and scrubs every surface — floor, walls, and the waterline — using rotating brushes and powerful filtration. Handles pools up to 50 feet, filters debris down to 2 microns, and climbs walls with dual traction treads. Schedule it from the app.", specs: { pool_size: "Up to 50 ft", filtration: "2 micron", cycle: "2.5 hours", cable: "60 ft swivel", weight: "9 kg" }, highlight: "Underwater Cleaning", tags: ["pool", "underwater", "scrubbing"], rating: 4.5, in_stock: true },
  { id: 8, name: "Nexus AirPure", category: "Home Cleaner", price: 699, image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=300&fit=crop", short_desc: "Mobile air purifying robot that moves to the dirtiest air zone in your home automatically.", description: "Unlike stationary purifiers, AirPure drives to where the air quality is worst. It continuously monitors PM2.5, VOCs, humidity, and CO2 across rooms, then positions itself for maximum effect. HEPA H13 filter captures 99.97% of particles. Quiet night mode at just 28 dB.", specs: { filter: "HEPA H13", coverage: "800 sqft", sensors: "PM2.5 + VOC + CO2 + Humidity", noise: "28-52 dB", battery: "8 hours" }, highlight: "Mobile Purification", tags: ["air quality", "purifier", "mobile"], rating: 4.4, in_stock: true },
  { id: 9, name: "Nexus Buddy", category: "Child", price: 399, image: "https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?w=400&h=300&fit=crop", short_desc: "Interactive play companion for kids aged 3-8 that tells stories, plays games, and teaches manners.", description: "Nexus Buddy is a soft, round, and huggable robot designed for young children. It tells bedtime stories with sound effects, plays quiz games, teaches basic math and alphabets, dances to music, and responds to touch and voice. Fully child-safe with no sharp edges and parental controls via app.", specs: { age: "3-8 years", battery: "8 hours", material: "Food-grade silicone shell", weight: "1.2 kg", parental_controls: "Full app control" }, highlight: "Safest for Toddlers", tags: ["play", "stories", "toddler-safe"], rating: 4.9, in_stock: true },
  { id: 10, name: "Nexus CodePal", category: "Child", price: 249, image: "https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=400&h=300&fit=crop", short_desc: "Block-coding robot that teaches kids aged 6-12 programming logic through physical play.", description: "CodePal comes with color-coded physical blocks that snap together to create programs. Place the blocks in sequence, press play, and watch the robot execute your code — move forward, turn, flash LEDs, make sounds. Graduates to a tablet app with Scratch-style visual coding for older kids.", specs: { age: "6-12 years", blocks: "40 coding blocks", battery: "6 hours", connectivity: "Bluetooth 5.0", weight: "0.8 kg" }, highlight: "Learn Coding", tags: ["coding", "STEM", "block-programming"], rating: 4.8, in_stock: true },
  { id: 11, name: "Nexus Tutor", category: "Child", price: 599, image: "https://images.unsplash.com/photo-1531746790095-e5995e348a01?w=400&h=300&fit=crop", short_desc: "AI homework helper for kids aged 8-15 that explains concepts in math, science, and languages.", description: "Nexus Tutor sits on the study desk and acts as a patient, always-available tutor. Point your textbook at its camera and it explains the concept step-by-step. It adapts difficulty to the child level, tracks progress, gives practice problems, and sends weekly reports to parents. Covers math, science, English, and 5 other languages.", specs: { age: "8-15 years", camera: "5MP document scanner", display: "7-inch", subjects: "Math, Science, English + 5 languages", battery: "5 hours" }, highlight: "AI Tutoring", tags: ["homework", "tutoring", "adaptive learning"], rating: 4.6, in_stock: true },
  { id: 12, name: "Nexus BuildKit", category: "Educational", price: 799, image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400&h=300&fit=crop", short_desc: "Modular robotics kit for schools with 20+ buildable configurations and Python support.", description: "BuildKit is designed for school robotics labs. Students assemble robots from modular parts — wheels, arms, sensors, grippers — and program them in Python or block-based code. Includes curriculum guides for teachers, 20+ project ideas, and a classroom dashboard to track student progress.", specs: { configs: "20+ builds", programming: "Python + Blockly", parts: "180 pieces", sensors: "8 types (IR, ultrasonic, color, gyro...)", weight: "3.5 kg" }, highlight: "Most Versatile Kit", tags: ["modular", "school lab", "Python"], rating: 4.7, in_stock: true },
  { id: 13, name: "Nexus ROS Lab", category: "Educational", price: 2999, image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop", short_desc: "University-grade research robot with ROS2, SLAM, and computer vision out of the box.", description: "Nexus ROS Lab is built for university robotics courses and research projects. It runs ROS2 natively on a Jetson Orin Nano, has stereo cameras for depth perception, a 2D LiDAR for SLAM, and a 4-DOF arm for manipulation tasks. Fully documented with lab exercise guides for professors.", specs: { compute: "Jetson Orin Nano 8GB", lidar: "RPLiDAR A1", camera: "Stereo depth camera", arm: "4-DOF with gripper", platform: "ROS2 Humble" }, highlight: "Research Grade", tags: ["ROS2", "university", "SLAM", "research"], rating: 4.6, in_stock: true },
  { id: 14, name: "Nexus CompeteBot", category: "Educational", price: 1499, image: "https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=400&h=300&fit=crop", short_desc: "Competition-ready robot platform for RoboWars, line-following, and maze-solving contests.", description: "Built for robotics competitions. CompeteBot has a high-torque drivetrain for speed events, swappable sensor modules for different contest types, and a quick-swap battery system for back-to-back rounds. Aluminum chassis can take hits in combat events. Used by 200+ teams in national competitions.", specs: { speed: "2.5 m/s max", torque: "12 kg-cm motors", chassis: "6061 aluminum", battery: "Hot-swappable LiPo", weight: "4.8 kg" }, highlight: "Competition Ready", tags: ["competition", "speed", "combat"], rating: 4.5, in_stock: false },
  { id: 15, name: "Nexus SimBot", category: "Educational", price: 449, image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop", short_desc: "Affordable classroom robot with digital twin — test code in simulation before running on hardware.", description: "SimBot bridges the gap between simulation and reality. Every SimBot has a digital twin in the included Gazebo-based simulator, so students can test and debug code virtually before deploying to the physical robot. Great for schools that want to teach robotics without risking expensive hardware breakage.", specs: { simulator: "Gazebo + custom GUI", programming: "Python + C++", sensors: "Camera + IMU + 4 IR", battery: "4 hours", weight: "1.8 kg" }, highlight: "Digital Twin", tags: ["simulation", "digital twin", "classroom"], rating: 4.4, in_stock: true },
  { id: 16, name: "Nexus WatchDog", category: "Security", price: 1899, image: "https://images.unsplash.com/photo-1563968743333-044cef800494?w=400&h=300&fit=crop", short_desc: "Autonomous home patrol robot that roams your property and detects intruders day and night.", description: "WatchDog patrols your home perimeter on a schedule or on-demand. It uses night vision and thermal imaging to detect people, animals, or vehicles, and sends instant alerts with video clips to your phone. Features a loud siren, two-way audio to talk to visitors, and weatherproof IP65 build for outdoor use.", specs: { camera: "4K + Night vision + Thermal", battery: "16 hours", speed: "6 km/h", build: "IP65 weatherproof", siren: "105 dB" }, highlight: "Outdoor Patrol", tags: ["patrol", "night vision", "outdoor"], rating: 4.6, in_stock: true },
  { id: 17, name: "Nexus EyeNet", category: "Security", price: 799, image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=400&h=300&fit=crop", short_desc: "Indoor security robot that maps your home and provides 24/7 AI-powered monitoring.", description: "EyeNet quietly rolls through your home monitoring for break-ins, fire, smoke, gas leaks, and water leaks. Its AI distinguishes between family members, pets, and strangers — so you only get alerts that matter. Auto-docks to charge and resumes patrol. Integrates with existing home security systems.", specs: { camera: "2K HDR + IR night vision", sensors: "Smoke + Gas + Water leak", battery: "12 hours", noise: "30 dB (whisper quiet)", weight: "3.5 kg" }, highlight: "Multi-Hazard Detection", tags: ["indoor", "fire detection", "smart alerts"], rating: 4.5, in_stock: true },
  { id: 18, name: "Nexus SkyGuard", category: "Security", price: 2499, image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&h=300&fit=crop", short_desc: "Security drone that auto-launches when sensors are triggered and live-streams aerial footage.", description: "SkyGuard sits in its charging dock on your roof or balcony. When your perimeter sensors detect movement, it auto-launches in 10 seconds, flies to the location, and streams live aerial footage to your phone and local security. Tracks moving subjects with AI lock-on and records everything in 4K.", specs: { flight: "25 min", launch: "10 sec auto-deploy", camera: "4K gimbal-stabilized", range: "500 m radius", charging: "Auto-dock rooftop" }, highlight: "Aerial Response", tags: ["drone", "auto-launch", "aerial"], rating: 4.4, in_stock: true },
  { id: 19, name: "Nexus LiftMax", category: "Industrial", price: 18999, image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&fit=crop", short_desc: "Heavy-duty warehouse robot that moves pallets and crates up to 500kg autonomously.", description: "LiftMax is built for warehouses and factory floors. It lifts and transports pallets up to 500kg, navigates narrow aisles with centimeter precision, and integrates with warehouse management systems for automated order fulfillment. Runs 20-hour shifts and auto-charges in 45 minutes.", specs: { payload: "500 kg", speed: "1.8 m/s", battery: "20 hours", charging: "45 min fast-charge", navigation: "LiDAR + floor markers" }, highlight: "Heaviest Payload", tags: ["warehouse", "heavy lifting", "logistics"], rating: 4.7, in_stock: true },
  { id: 20, name: "Nexus ArmX6", category: "Industrial", price: 34999, image: "https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=400&h=300&fit=crop", short_desc: "6-axis precision robotic arm for assembly, welding, and pick-and-place at 0.02mm accuracy.", description: "ArmX6 is a professional 6-axis robotic arm for production lines. It handles welding, assembly, painting, and pick-and-place with 0.02mm repeatability. Teach it new tasks by physically guiding the arm — no programming needed for simple operations. ISO safety certified for human-collaborative zones.", specs: { payload: "20 kg", reach: "1.8 m", repeatability: "±0.02 mm", axes: 6, safety: "ISO 10218 + ISO/TS 15066" }, highlight: "Highest Precision", tags: ["robotic arm", "welding", "assembly"], rating: 4.8, in_stock: true },
  { id: 21, name: "Nexus SortFlow", category: "Industrial", price: 12499, image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=300&fit=crop", short_desc: "High-speed package sorting robot that reads labels and routes 3000 parcels per hour.", description: "SortFlow sits on your conveyor line and sorts packages at blazing speed. Its vision AI reads barcodes, QR codes, and shipping labels regardless of orientation, then diverts packages to the correct chute. Handles parcels from envelopes to 30kg boxes. Integrates with all major shipping APIs.", specs: { speed: "3000 parcels/hr", payload: "30 kg max", vision: "360° barcode/QR/OCR", uptime: "99.5%", integration: "REST API + WMS plugins" }, highlight: "Fastest Sorting", tags: ["sorting", "logistics", "high-speed"], rating: 4.6, in_stock: true },
  { id: 22, name: "Nexus InspectEye", category: "Industrial", price: 8999, image: "https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?w=400&h=300&fit=crop", short_desc: "Quality inspection robot with AI vision that catches defects human eyes miss.", description: "InspectEye sits at the end of your production line and inspects every unit at full line speed. Its multi-camera AI system detects surface scratches, color mismatches, missing components, and dimensional errors down to 0.1mm. Rejects defective items automatically and generates quality reports.", specs: { cameras: "4x 20MP industrial", detection: "0.1mm defects", speed: "120 units/min", lighting: "Multi-angle LED array", interface: "Ethernet + OPC-UA" }, highlight: "AI Quality Control", tags: ["inspection", "quality", "defect detection"], rating: 4.5, in_stock: false }
];

// Insert products
const insertStmt = db.prepare(`
  INSERT OR REPLACE INTO products (id, name, category, price, image, short_desc, description, specs, highlight, tags, rating, in_stock)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const insertMany = db.transaction((products) => {
  for (const p of products) {
    insertStmt.run(
      p.id,
      p.name,
      p.category,
      p.price,
      p.image,
      p.short_desc,
      p.description,
      JSON.stringify(p.specs),
      p.highlight,
      JSON.stringify(p.tags),
      p.rating,
      p.in_stock ? 1 : 0
    );
  }
});

insertMany(robots);

console.log(`Seeded ${robots.length} products successfully!`);
