-- SQLite-compatible seed data for Nexus Bots
-- Strict dataset: 12 robots, 4 categories (Kitchen, Home Cleaner, Drone, Humanoid)

INSERT OR REPLACE INTO products (id, name, brand, category, price, image, short_desc, description, specs, highlight, tags, rating, in_stock) VALUES
(1, 'Amazon Astro', 'Amazon', 'Kitchen', 1599.99, 'https://source.unsplash.com/1200x900/?kitchen,robot,assistant&sig=101', 'Kitchen-focused smart assistant for reminders, timers, and hands-free controls.', 'Built for smart kitchens where users need hands-free reminders, voice commands, and quick monitoring while cooking.', '{"display":"10-inch HD","battery":"Up to 5 hours","assistant":"Alexa built-in","camera":"1080p periscope","navigation":"Visual SLAM","connectivity":"Wi-Fi 6 + Bluetooth"}', 'Kitchen Voice Assistant', '["kitchen","assistant","alexa","smart home"]', 4.3, 1),
(2, 'Samsung Ballie', 'Samsung', 'Kitchen', 1299.99, 'https://source.unsplash.com/1200x900/?kitchen,smart,robot&sig=102', 'Rolling AI kitchen companion with projector and smart appliance coordination.', 'Designed for interactive kitchen assistance where visual prompts and automated appliance control improve meal preparation.', '{"projector":"1080p built-in","processor":"Edge AI chip","connectivity":"Wi-Fi 6E","battery":"Up to 3 hours","sensors":"ToF + camera array","control":"SmartThings integration"}', 'Kitchen Companion', '["kitchen","projector","assistant","smart appliances"]', 4.5, 0),
(3, 'Enabot EBO X', 'Enabot', 'Kitchen', 599.99, 'https://source.unsplash.com/1200x900/?kitchen,monitoring,robot&sig=103', 'Compact kitchen monitoring robot with 4K camera and remote communication.', 'Ideal for monitoring kitchen safety, checking appliances remotely, and staying connected through two-way audio.', '{"camera":"4K ultra-wide","audio":"Two-way speaker + mic","navigation":"LiDAR SLAM","nightVision":"Infrared mode","battery":"Up to 4 hours","docking":"Auto-return charging"}', 'Kitchen Monitoring', '["kitchen","camera","monitoring","remote"]', 4.4, 1),
(4, 'iRobot Roomba j9+', 'iRobot', 'Home Cleaner', 799.99, 'https://source.unsplash.com/1200x900/?robot,vacuum,home&sig=104', 'Self-emptying robot vacuum with smart mapping.', 'Made for daily autonomous floor cleaning in homes with minimal manual intervention.', '{"runtime":"Up to 75 minutes","navigation":"PrecisionVision","dock":"Auto-empty Clean Base","suction":"3-stage cleaning","control":"App scheduling + zones","voice":"Alexa + Google Assistant"}', 'Smart Vacuum', '["vacuum","auto-empty","mapping"]', 4.5, 1),
(5, 'Roborock S8 MaxV Ultra', 'Roborock', 'Home Cleaner', 1799.99, 'https://source.unsplash.com/1200x900/?robot,mop,cleaning&sig=105', 'High-end vacuum and mop with auto wash and auto dry dock.', 'Best for premium whole-home cleaning with combined vacuuming, mopping, and self-maintenance dock cycles.', '{"suction":"10,000 Pa","runtime":"Up to 180 minutes","dock":"Auto-empty + wash + dry","navigation":"LiDAR + Reactive AI","mopping":"Dual vibra-rise system","mapping":"Multi-floor smart maps"}', 'Vacuum + Mop Combo', '["vacuum","mop","auto-dock"]', 4.7, 1),
(6, 'Ecovacs WINBOT W2 Omni', 'Ecovacs', 'Home Cleaner', 499.99, 'https://source.unsplash.com/1200x900/?window,cleaning,robot&sig=106', 'Window cleaning robot with edge detection and auto-spray.', 'Purpose-built for automated glass cleaning on windows where safety and edge detection are critical.', '{"navigation":"WIN-SLAM 4.0","suction":"2800 Pa","safety":"Anti-fall detection","cleaning":"Auto spray + microfiber wipe","compatibility":"Framed + frameless glass","noise":"Low-noise mode"}', 'Window Cleaner', '["window","cleaning","auto-spray"]', 4.2, 0),
(7, 'Ring Always Home Cam', 'Ring (Amazon)', 'Drone', 249.99, 'https://source.unsplash.com/1200x900/?indoor,drone,camera&sig=107', 'Autonomous indoor flying drone for home patrol.', 'Intended for indoor security patrols where homeowners need quick, automated visual checks.', '{"camera":"1080p HD","flight":"Up to 5 minutes","charging":"Auto-dock","navigation":"Obstacle avoidance","integration":"Ring Alarm ecosystem","control":"Mobile app route presets"}', 'Indoor Patrol Drone', '["drone","security","indoor","patrol"]', 4.1, 1),
(8, 'DJI Matrice 30T', 'DJI', 'Drone', 13600.00, 'https://source.unsplash.com/1200x900/?industrial,drone,inspection&sig=108', 'Enterprise drone with thermal and zoom cameras.', 'Built for enterprise inspection, emergency response, and thermal surveying in challenging outdoor conditions.', '{"camera":"48MP + thermal","flight":"Up to 41 minutes","weatherproof":"IP55","zoom":"200x hybrid","transmission":"Long-range encrypted link","safety":"Multi-sensor obstacle avoidance"}', 'Thermal Drone', '["drone","thermal","enterprise","inspection"]', 4.7, 1),
(9, 'Aiper Surfer S1', 'Aiper', 'Drone', 1399.99, 'https://source.unsplash.com/1200x900/?pool,cleaning,drone&sig=109', 'Autonomous surface cleaning drone for pools.', 'Developed for automated pool surface cleaning, debris collection, and routine maintenance patrols.', '{"navigation":"Sonar guidance","runtime":"Up to 90 minutes","coverage":"Up to 2,150 sq ft","filtration":"Fine debris mesh","charging":"Dock-ready charging","control":"Mobile app scheduling"}', 'Pool Surface Drone', '["drone","pool","autonomous","cleaning"]', 4.4, 0),
(10, 'Miko 3', 'Miko', 'Humanoid', 249.99, 'https://source.unsplash.com/1200x900/?humanoid,robot,kid&sig=110', 'Interactive humanoid-style companion for kids.', 'Created as a child-friendly humanoid companion for learning support, engagement, and interactive play.', '{"ageRange":"5-12 years","activities":"1000+ sessions","battery":"Up to 7 hours","ai":"Conversational + adaptive","connectivity":"Wi-Fi","parentalControls":"Companion app"}', 'Kids Companion', '["humanoid","kids","learning","AI"]', 4.6, 1),
(11, 'Wonder Workshop Dash', 'Wonder Workshop', 'Humanoid', 149.99, 'https://source.unsplash.com/1200x900/?educational,robot,child&sig=111', 'Programmable educational robot with expressive interaction.', 'Focused on introducing coding logic and computational thinking through a humanoid-style interactive robot.', '{"programming":"Blockly","connectivity":"Bluetooth","battery":"Up to 5 hours","sensors":"Proximity + microphone","ageRange":"6-11 years","classroomUse":"STEM curriculum ready"}', 'Coding Robot', '["humanoid","coding","education","STEM"]', 4.7, 1),
(12, 'LEGO Education Spike Prime', 'LEGO', 'Humanoid', 395.95, 'https://source.unsplash.com/1200x900/?classroom,robotics,kit&sig=112', 'Build-and-program humanoid robotics kit for classroom projects.', 'Intended for structured classroom robotics projects where students build humanoid concepts and program behaviors.', '{"pieces":"523","programming":"Scratch + Python","hub":"6-port programmable hub","sensors":"Color + distance + force","motors":"3 included motors","curriculum":"40+ guided lessons"}', 'Classroom Robotics Kit', '["humanoid","LEGO","python","classroom"]', 4.8, 0);