-- SQLite-compatible seed data for Nexus Bots
-- This file mirrors the data in init.js and client/src/data/robots.js
-- To seed: npm run init-db (uses init.js which reads schema.sql + inserts directly)
-- This SQL file is for reference / manual seeding if needed

INSERT OR REPLACE INTO products (id, name, brand, category, price, image, short_desc, description, specs, highlight, tags, rating, in_stock) VALUES
(1, 'Amazon Astro', 'Amazon', 'Household', 1599.99, 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop', 'Home intelligence robot with Alexa, autonomous patrol, and person recognition.', 'Amazon Astro is a home robot that uses AI to help you around the house. It can patrol your home when you''re away, send you alerts if it detects something unusual, and recognize familiar faces. With Alexa built in, it can play music, set timers, make video calls, and control smart home devices. It navigates autonomously using SLAM and avoids obstacles in real time.', '{"display":"10-inch HD","battery":"5+ hours","navigation":"Visual SLAM + LiDAR","weight":"7.7 kg","assistant":"Alexa built-in","camera":"Periscope 1080p"}', 'Smart Home AI', '["alexa","home patrol","person recognition","smart home"]', 4.3, 1),

(2, 'Samsung Ballie', 'Samsung', 'Household', 1299.99, 'https://images.unsplash.com/photo-1546776310-eef45dd6d63c?w=400&h=300&fit=crop', 'Rolling AI companion robot with built-in projector, spatial awareness, and smart home control.', 'Samsung Ballie is a ball-shaped AI companion that rolls around your home autonomously. It features a built-in projector that can display content on any wall, spatial awareness to understand your home layout, and natural language interaction. Ballie can control smart appliances, follow you from room to room, and provide personalized assistance based on your habits.', '{"projector":"1080p built-in","processor":"Edge AI chip","connectivity":"Wi-Fi 6E + BT 5.3","weight":"1.3 kg","navigation":"Spatial AI + ToF sensor","battery":"3+ hours"}', 'Built-in Projector', '["projector","AI companion","spatial awareness","smart home"]', 4.5, 0),

(3, 'Enabot EBO X', 'Enabot', 'Household', 599.99, 'https://images.unsplash.com/photo-1589254065878-42c014d8834b?w=400&h=300&fit=crop', 'Family companion robot with 4K camera, two-way audio, and autonomous monitoring.', 'Enabot EBO X is a family companion robot that patrols your home, provides live 4K video streaming, and offers two-way audio so you can communicate remotely. It auto-navigates using LiDAR, returns to its charging dock when low on battery, and features night vision for 24/7 monitoring. The companion app lets you drive it remotely or set patrol schedules.', '{"camera":"4K wide-angle","audio":"2-way speaker + mic","navigation":"LiDAR SLAM","battery":"4 hours","night_vision":"IR night vision","weight":"0.7 kg"}', 'Remote Monitoring', '["4K camera","two-way audio","night vision","family"]', 4.4, 1),

(4, 'Unitree Go2 Air', 'Unitree', 'Household', 1599.99, 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=400&h=300&fit=crop', 'Quadruped robot dog with 4D LiDAR, intelligent following, and voice command support.', 'Unitree Go2 Air is a consumer quadruped robot that walks, runs, and navigates complex terrain. It features 4D LiDAR for spatial mapping, intelligent following mode, voice command recognition, and can perform tricks and dances. With 12 degrees of freedom and advanced motion control, it moves naturally and recovers from stumbles. Companion app provides remote control and programming.', '{"dof":"12 joints","lidar":"4D LiDAR L1","speed":"3.5 m/s max","battery":"1-2 hours","weight":"15 kg","compute":"8-core CPU + 4 TOPS NPU"}', 'Quadruped Robot Dog', '["quadruped","robot dog","LiDAR","voice commands"]', 4.6, 1),

(5, 'iRobot Roomba j9+', 'iRobot', 'Home Cleaner', 799.99, 'https://images.unsplash.com/photo-1518314916381-77a37c2a49ae?w=400&h=300&fit=crop', 'Self-emptying robot vacuum with PrecisionVision navigation and smart mapping.', 'iRobot Roomba j9+ uses PrecisionVision navigation to identify and avoid obstacles like pet waste, shoes, and cords. It maps your home room-by-room, lets you set cleaning schedules per room, and automatically empties its dustbin into the Clean Base. iRobot OS learns your cleaning habits and suggests schedules. Works with Alexa and Google Assistant.', '{"suction":"3-stage cleaning system","runtime":"75 minutes","dustbin":"Auto-empty Clean Base","navigation":"PrecisionVision","noise":"65 dB","connectivity":"Wi-Fi + Alexa + Google"}', 'Smart Obstacle Avoidance', '["vacuum","auto-empty","obstacle avoidance","smart mapping"]', 4.5, 1),

(6, 'Roborock S8 MaxV Ultra', 'Roborock', 'Home Cleaner', 1799.99, 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=300&fit=crop', 'Robot vacuum and mop with 10,000Pa suction, ReactiveAI 2.0, and auto wash-dry dock.', 'Roborock S8 MaxV Ultra is a premium robot vacuum and mop combo with 10,000Pa suction power — the strongest in its class. ReactiveAI 2.0 uses a dual camera and 3D structured light to recognize and avoid 50+ types of obstacles. The RockDock Ultra auto-empties dustbin, auto-washes mop pads with hot water, and auto-dries them. Supports multi-floor mapping.', '{"suction":"10,000 Pa","runtime":"180 minutes","navigation":"LiDAR + ReactiveAI 2.0","dock":"Auto-empty + wash + dry","mopping":"Sonic vibration 4000 RPM","weight":"4.8 kg"}', 'Strongest Suction', '["vacuum","mop","10000Pa","auto-dock","ReactiveAI"]', 4.7, 1),

(7, 'Ecovacs WINBOT W2 Omni', 'Ecovacs', 'Home Cleaner', 499.99, 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400&h=300&fit=crop', 'Window cleaning robot with WIN-SLAM 4.0 navigation, edge detection, and auto-spray.', 'Ecovacs WINBOT W2 Omni sticks to glass surfaces using strong suction and cleans windows autonomously using WIN-SLAM 4.0 path planning. It detects window edges, plans the most efficient cleaning route, and features a built-in water spray system for streak-free cleaning. Anti-fall sensors and a safety rope backup prevent drops. Works on framed and frameless windows.', '{"navigation":"WIN-SLAM 4.0","suction":"2800 Pa","cleaning":"Auto-spray + wipe","safety":"Anti-fall + backup rope","noise":"62 dB","weight":"1.9 kg"}', 'Window Cleaning Specialist', '["window cleaning","suction-grip","auto-spray","edge detection"]', 4.2, 1),

(8, 'Aiper Surfer S1', 'Aiper', 'Home Cleaner', 1399.99, 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop', 'Cordless robotic pool cleaner with sonar navigation, wall climbing, and app control.', 'Aiper Surfer S1 is a cordless robotic pool cleaner that uses SurrealSense sonar navigation to map your pool and clean the floor, walls, and waterline. It climbs walls with quad-motor traction, filters debris down to fine particles, and returns to the docking station when done. The Aiper app lets you schedule cleaning, set zones, and monitor filter status remotely.', '{"navigation":"SurrealSense sonar","runtime":"90 minutes","coverage":"Up to 2,150 sq ft pool","cleaning":"Floor + walls + waterline","filtration":"Fine debris filter","weight":"8.2 kg"}', 'Cordless Pool Cleaning', '["pool cleaner","cordless","sonar navigation","wall climbing"]', 4.4, 1),

(9, 'Miko 3', 'Miko', 'Child', 249.99, 'https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?w=400&h=300&fit=crop', 'AI robot companion for kids with emotional intelligence, 1000+ activities, and adaptive learning.', 'Miko 3 is an AI-powered companion robot designed for children aged 5-12. It features emotional intelligence — recognizing and responding to a child''s mood through voice tone and facial expressions. With over 1000 activities including stories, games, trivia, and guided meditations, Miko adapts its content difficulty based on the child''s learning level. Parents get weekly progress reports via the companion app.', '{"age":"5-12 years","ai":"Emotional AI + adaptive learning","activities":"1000+","battery":"7 hours","weight":"1.1 kg","connectivity":"Wi-Fi + BT"}', 'Emotional AI for Kids', '["kids","emotional AI","adaptive learning","stories"]', 4.6, 1),

(10, 'Wonder Workshop Dash', 'Wonder Workshop', 'Child', 149.99, 'https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=400&h=300&fit=crop', 'Award-winning coding robot for kids aged 6-11 with Blockly programming and voice commands.', 'Wonder Workshop Dash is an award-winning coding robot that teaches kids programming through play. Using the Blockly visual programming language in the Wonder app, kids can make Dash move, light up, make sounds, and respond to voice commands. Dash has proximity sensors, accelerometers, and microphones that enable interactive games and challenges. Used in 40,000+ schools worldwide.', '{"age":"6-11 years","programming":"Blockly (Wonder app)","sensors":"Proximity + accelerometer + mic","connectivity":"Bluetooth","battery":"5 hours","weight":"0.8 kg"}', 'Learn Coding Through Play', '["coding","Blockly","STEM","voice commands"]', 4.7, 1),

(11, 'LEGO Education Spike Prime', 'LEGO', 'Child', 395.95, 'https://images.unsplash.com/photo-1531746790095-e5995e348a01?w=400&h=300&fit=crop', 'STEM robotics kit with 523 LEGO pieces, Python and Scratch coding, and 6 sensor ports.', 'LEGO Education Spike Prime combines LEGO building elements with a programmable hub, motors, and sensors to teach coding and engineering. Students build robots and program them using Scratch-based blocks or Python. The kit includes 523 pieces, a 6-port programmable hub with gyroscope, and sensors for color, distance, and force. Comes with 40+ hours of curriculum-aligned lesson plans.', '{"age":"10+ years","pieces":"523 LEGO elements","hub":"6-port programmable","programming":"Scratch + Python","sensors":"Color + Distance + Force","motors":"2x Medium + 1x Large"}', 'LEGO + Python Coding', '["LEGO","Python","Scratch","STEM","building"]', 4.8, 1),

(12, 'DJI RoboMaster S1', 'DJI', 'Educational', 549.00, 'https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=400&h=300&fit=crop', 'Competition-grade educational robot with mecanum wheels, FPV camera, and AI modules.', 'DJI RoboMaster S1 is an advanced educational robot inspired by DJI''s RoboMaster competition. It features mecanum wheels for omnidirectional movement, a first-person view camera, a gel bead blaster for competitive play, and AI modules including line following, person recognition, and clap detection. Programmable in Scratch and Python with a visual curriculum of 50+ lessons.', '{"drive":"4x Mecanum wheels","camera":"FPV 1080p","ai":"Line follow + person recognition + clap detect","programming":"Scratch 3.0 + Python","speed":"3.5 m/s","weight":"3.3 kg"}', 'Competition Grade', '["mecanum wheels","FPV","Python","competition","AI modules"]', 4.5, 1),

(13, 'TurtleBot 4 Standard', 'Clearpath Robotics', 'Educational', 1869.00, 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400&h=300&fit=crop', 'ROS 2 development platform with OAK-D camera, LiDAR, and iRobot Create 3 mobile base.', 'TurtleBot 4 is the standard platform for learning and developing with ROS 2 (Robot Operating System). Built on the iRobot Create 3 mobile base, it features a Raspberry Pi 4, Luxonis OAK-D stereo camera for depth perception, and a 2D RPLiDAR for SLAM and navigation. Officially supported by Open Robotics with extensive documentation, tutorials, and community packages.', '{"compute":"Raspberry Pi 4 (4GB)","camera":"OAK-D stereo depth","lidar":"RPLiDAR A1M8","base":"iRobot Create 3","platform":"ROS 2 Humble","battery":"2.6 hours"}', 'Official ROS 2 Platform', '["ROS2","SLAM","depth camera","university","research"]', 4.4, 1),

(14, 'Makeblock mBot2', 'Makeblock', 'Educational', 159.00, 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop', 'Classroom coding robot with CyberPi brain, Wi-Fi networking, and multi-sensor suite.', 'Makeblock mBot2 is a next-generation classroom coding robot powered by the CyberPi microcontroller with built-in Wi-Fi. It features ultrasonic, color, and line-following sensors, a gyroscope, and a speaker. Students program it using mBlock IDE (Scratch-based) or Python. Supports multi-robot networking for collaborative classroom activities. Used in 20,000+ schools across 140+ countries.', '{"brain":"CyberPi (ESP32)","sensors":"Ultrasonic + color + line + gyro","programming":"mBlock (Scratch) + Python","connectivity":"Wi-Fi + Bluetooth","motor":"2x encoder motors","weight":"1.1 kg"}', 'Best for Classrooms', '["classroom","mBlock","Python","multi-robot","WiFi"]', 4.5, 1),

(15, 'Unitree Go2 EDU', 'Unitree', 'Educational', 2800.00, 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop', 'Quadruped research platform with ROS 2 support, 4D LiDAR, and full SDK access.', 'Unitree Go2 EDU is the research-grade version of the Go2 quadruped robot, offering full SDK access, ROS 2 compatibility, and advanced sensor suite. Researchers and students can program custom gaits, develop autonomous navigation algorithms, and integrate additional hardware. Features 4D LiDAR for mapping, 12 high-torque joints for agile movement, and an onboard GPU for edge AI processing.', '{"dof":"12 joints","lidar":"4D LiDAR L1","compute":"NVIDIA Jetson (8 TOPS)","platform":"ROS 2 + SDK","battery":"2 hours","weight":"15 kg"}', 'Quadruped Research Platform', '["quadruped","ROS2","SDK","research","LiDAR"]', 4.6, 0),

(16, 'Ring Always Home Cam', 'Ring (Amazon)', 'Security', 249.99, 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&h=300&fit=crop', 'Autonomous indoor security drone that flies preset patrol routes and streams live video.', 'Ring Always Home Cam is an autonomous indoor security drone that flies preset routes through your home when triggered by Ring Alarm sensors or on demand via the app. It provides live 1080p video from any room, lands in its dock to charge and block the camera for privacy, and integrates with the Ring ecosystem. Compact and lightweight, it navigates around furniture using obstacle avoidance sensors.', '{"camera":"1080p HD","flight":"5 minutes per route","navigation":"Obstacle avoidance sensors","integration":"Ring Alarm + Alexa","charging":"Auto-dock","weight":"0.18 kg"}', 'Indoor Flying Drone', '["indoor drone","Ring","security camera","auto-patrol"]', 4.1, 1),

(17, 'Xiaomi CyberDog 2', 'Xiaomi', 'Security', 2999.99, 'https://images.unsplash.com/photo-1563968743333-044cef800494?w=400&h=300&fit=crop', 'Quadruped patrol robot with 19 sensors, NVIDIA NX processing, and 150-minute battery.', 'Xiaomi CyberDog 2 is a quadruped robot designed for patrol and security applications. Powered by NVIDIA Jetson NX, it carries 19 sensors including cameras, LiDAR, ultrasonic, and ToF for full environmental awareness. It can patrol autonomously, detect and track moving subjects, navigate stairs and rough terrain, and alert you via the app. With voice AI built in, it responds to commands naturally.', '{"compute":"NVIDIA Jetson NX","sensors":"19 (camera + LiDAR + ultrasonic + ToF)","battery":"150 minutes","speed":"1.6 m/s","weight":"8.9 kg","voice":"AI voice interaction"}', 'Quadruped Patrol Robot', '["quadruped","patrol","NVIDIA","19 sensors","terrain"]', 4.3, 1),

(18, 'DJI Matrice 30T', 'DJI', 'Security', 13600.00, 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=400&h=300&fit=crop', 'Enterprise-grade security drone with 48MP camera, thermal imaging, and 41-minute flight time.', 'DJI Matrice 30T is a compact enterprise drone built for security, search and rescue, and infrastructure inspection. It carries a 48MP wide camera, a 48MP zoom camera (200x max zoom), and a 640x512 thermal sensor for detecting heat signatures at night. With IP55 weatherproofing, it operates in rain, dust, and extreme temperatures. DJI FlightHub 2 enables multi-drone fleet management.', '{"camera":"48MP wide + 48MP zoom + thermal","flight":"41 minutes","range":"15 km","weatherproof":"IP55","zoom":"200x max","weight":"3.77 kg"}', 'Thermal + 200x Zoom', '["enterprise drone","thermal imaging","48MP","IP55"]', 4.7, 1),

(19, 'Universal Robots UR10e', 'Universal Robots', 'Industrial', 35000.00, 'https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=400&h=300&fit=crop', 'Collaborative 6-axis robot arm with 12.5kg payload, 1300mm reach, and force sensing.', 'Universal Robots UR10e is a collaborative robot (cobot) designed to work safely alongside humans without safety cages. With 12.5kg payload capacity and 1300mm reach, it handles palletizing, machine tending, packaging, and assembly. The built-in force/torque sensor enables sensitive tasks like polishing and insertion. Program it by physically guiding the arm — no coding required for simple tasks. Certified to ISO 10218 and ISO/TS 15066.', '{"payload":"12.5 kg","reach":"1300 mm","axes":"6","repeatability":"±0.05 mm","weight":"33.5 kg","safety":"ISO 10218 + ISO/TS 15066"}', 'Collaborative Cobot', '["cobot","6-axis","force sensing","no-code programming"]', 4.8, 1),

(20, 'Boston Dynamics Stretch', 'Boston Dynamics', 'Industrial', 65000.00, 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=300&fit=crop', 'Warehouse logistics robot that unloads trucks and moves up to 800 cases per hour.', 'Boston Dynamics Stretch is a mobile robot designed for warehouse logistics. Its custom-designed arm with vacuum gripper can unload trucks and containers at up to 800 cases per hour. The perception system uses machine learning to identify and handle a wide variety of box sizes and weights. Stretch moves on a compact, wheeled base that navigates warehouse floors autonomously and can be deployed in under a day with minimal facility changes.', '{"throughput":"800 cases/hr","payload":"23 kg","reach":"Custom arm + vacuum gripper","navigation":"Autonomous mobile base","perception":"ML vision system","weight":"~1200 kg"}', '800 Cases/Hour', '["warehouse","truck unloading","logistics","mobile robot"]', 4.7, 0),

(21, 'FANUC CRX-25iA', 'FANUC', 'Industrial', 50000.00, 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=400&h=300&fit=crop', 'Industrial collaborative robot with 25kg payload, 1889mm reach, and IP67 protection.', 'FANUC CRX-25iA is one of the highest-payload collaborative robots available. With 25kg payload and 1889mm reach, it handles heavy palletizing, machine loading, and material handling tasks that most cobots cannot. The CRX series features intuitive tablet-based programming with drag-and-drop logic, and contact-stop safety sensors along the entire arm surface. IP67-rated for dusty and wet environments.', '{"payload":"25 kg","reach":"1889 mm","axes":"6","protection":"IP67","programming":"Tablet drag-and-drop","repeatability":"±0.04 mm"}', 'Heaviest Cobot Payload', '["cobot","25kg payload","IP67","palletizing","tablet programming"]', 4.6, 1),

(22, 'ABB YuMi IRB 14000', 'ABB', 'Industrial', 40000.00, 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&fit=crop', 'Dual-arm collaborative robot with 14 axes, vision-guided assembly, and ±0.02mm precision.', 'ABB YuMi is the world''s first truly collaborative dual-arm robot. With 7 axes per arm (14 total), it mimics human-like dexterity for small-parts assembly, packaging, and testing. Each arm has 0.5kg payload with ±0.02mm repeatability. Built-in vision system guides precise component placement. Padded arms and inherently safe design allow it to work alongside humans without barriers. Ideal for electronics assembly and lab automation.', '{"arms":"2x 7-axis (14 total)","payload":"0.5 kg per arm","repeatability":"±0.02 mm","vision":"Integrated camera system","speed":"1500 mm/s per arm","weight":"38 kg"}', 'Dual-Arm Dexterity', '["dual-arm","14 axes","precision assembly","vision-guided"]', 4.5, 1);
